### ISSUE TITLE
Rule dependencies

### ISSUE THREAD

**Issue by SamVerschueren** [SamVerschueren/gh-lint-brainstorm#4]
Because `gh-lint` lints a remote repository, a lot of network requests have to be done. Different rules may work on the same file. An example is a `tests` rule that checks if `package.json` has the appropriate test property, and it is implemented (see [tests.js](https://github.com/SamVerschueren/gh-lint/blob/master/rules/tests.js#L14-L26)). Another rule checks if `package.json` has valid properties (see [valid-properties.js](https://github.com/SamVerschueren/gh-lint/blob/master/rules/valid-properties.js)).

It would be stupid if both rules download the same `package.json` file if it could only be requested once. So I came up with dependencies/tasks (a little bit like Gulp). A rule [specifies](https://github.com/SamVerschueren/gh-lint/blob/master/rules/valid-properties.js#L33) a list of dependencies and exports them in the `_dependencies` property.

``` js
exports._dependencies = ['pkg-loader'];
```

From this moment, all the files that has `pkg-loader` as dependency, will wait untill that task is completed which is defined in [tasks/pkg-loader.js](https://github.com/SamVerschueren/gh-lint/blob/master/tasks/pkg-loader.js). The result of those dependencies is injected in the rule function where the first two parameters are reserved.

``` js
module.exports = (repository, opts, pkg) => {
    //=> pkg holds the package.json data
};
```
##### AngularJS style

``` js
module.exports = ['pkg-loader', (repository, opts, pkg) => {
    //=> implement rule here
}];
```

---

Feedback regarding the syntax, idea, etc. is welcome!

// @sindresorhus @jvandemo

**Comment by jvandemo** [comment]
@SamVerschueren &mdash; The syntax makes sense I think.

AngularJS 1.x has a similar approach indeed where they accept either array notation:

``` javascript
['depOne', 'depTwo', function(depOne, depTwo){
  // ...
}];
```

or the use of a `$inject` property:

``` javascript
function someFunction(depOne, depTwo){
  // ...
}
someFunction.$inject = ['depOne', 'depTwo'];
```

The only difference is that the order in the array doesn't correspond exactly to the order in the arguments. Other than that I see no issues with the syntax.

Maybe @SindreSorhus has a different opinion?

**Comment by jvandemo** [comment]
@SamVerschueren &mdash; Quick question regarding the implementation:

From what I can see [pkg-loader](https://github.com/SamVerschueren/gh-lint/blob/master/tasks/pkg-loader.js) currently returns a function that you call to fetch a file.

Calling the function twice will also download the file twice, no? Or is `got` caching the result?

Keep up the great work!

**Comment by SamVerschueren** [comment]
> The only difference is that the order in the array doesn't correspond exactly to the order in the arguments. Other than that I see no issues with the syntax.

Yes I know, but the first two should always be implemented. Don't feel the need to name those properties like this

``` js
module.exports._dependencies = ['repository', 'options', 'pkg-loader'];
// or
module.exports._dependencies = ['pkg-loader', 'repository', 'options'];
```

It offers more flexibility, but makes things more complex. The dependencies will be complex enough for most people ;).

> Calling the function twice will also download the file twice, no? Or is got caching the result?

Calling the function twice indeed will download the file twice... BUT...

Actually, as I was looking into it, I noticed a bug :). So thanks for asking! The idea is to prevent this by iterating over all the rules and creating a map of all the tasks being used.

``` js
{
    'pkg-loader': Promise,
    'license-loader': Promise
}
```

Then iterate over all the rules again and do something like this

``` js
Promise.all(pick(tasks, mod._dependencies || []))
    .then(() => execRule);
```

Which will reuse the results of the task.

**Comment by jvandemo** [comment]
@SamVerschueren &mdash; That makes perfect sense!

> Don't feel the need to name those properties like this

I think it's fine to just start injecting the dependencies after the first 2 arguments, which are always fixed. If it's documented well, people will easily understand I think. 

> The idea is to prevent this by iterating over all the rules and creating a map of all the tasks being used.

That sounds like a good plan. Maybe you can even wrap calls to tasks in a `memoize` function to solve the problem generically.

Keep up the great work Sam! Love what you're doing!

**Comment by SamVerschueren** [comment]
> Maybe you can even wrap calls to tasks in a memoize function to solve the problem generically.

Will keep it in mind, thanks for the suggestion!

> Keep up the great work Sam! Love what you're doing!

Thanks :)

**Comment by sindresorhus** [comment]
I would just use disk caching for the files. That way they're only downloaded once no matter how many times they're called from different rules. No need to require the user to do anything.

**Comment by SamVerschueren** [comment]
The rules are executed at the same time. So if `rule1.js` and `rule2.js` both have `package.json` as dependency, they will check if it is cached on disk on the same time (more or less) which will not be the case and it will still be downloaded twice.

**Comment by sindresorhus** [comment]
You could decorate `got` and deduplicate the requests. Should be easy since we use promises.

``` js
const cache = [];

function get(url) {
    return cache[url] || cache[url] = got(url);
}
```

**Comment by SamVerschueren** [comment]
Alright, looks good! Thanks :).

**Comment by SamVerschueren** [comment]
Using [mem](https://github.com/sindresorhus/mem) for caching now :heart:
